name: Auto Release

on:
  schedule:
    - cron: "0 6 1 * *" # 1st of month, 06:00 UTC
  workflow_dispatch:

jobs:
  release:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-auto-release.yaml@f05ced3d809cc611520684c5621c5700c6132795 # main
    secrets: inherit
