name: "Maintenance: Renovate"

on:
  push:
    branches:
      - main
    paths:
      - .renovaterc.json5
  schedule:
    - cron: '0 * * * *' # Every hour
  issues:
    types:
      - edited
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: boolean
        default: false
      logLevel:
        description: Log Level
        default: debug
      version:
        description: Renovate Version
        default: latest

jobs:
  renovate:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-renovate.yaml@3b8ffc4e0443eb0241f4d7d2beb7b97e011c0c00 # main
    with:
      dryRun: ${{ inputs.dryRun && 'full' || '' }}
      logLevel: ${{ inputs.logLevel || 'debug' }}
      version: ${{ inputs.version || 'latest' }}
    secrets: inherit
